version: '2'
services:
  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "6066:80"
    volumes:
      - ./:/app
      - ./docker/symfony.conf:/etc/nginx/conf.d/symfony.conf:ro

  redis:
    image: redis

  php:
    build: ""
    environment:
      REDIS_URL: redis://redis
    depends_on:
      - redis
    volumes:
      - ./:/app
    working_dir: /app