services:
  App\WeatherProvider\WeatherProvider:
    arguments:
      - "@App\\LocationProvider\\LocationProvider"
      - "@App\\WeatherProvider\\Weatherbit"
      - "@App\\WeatherProvider\\OpenWeatherMap"
      - "@logger"
    public: true